server:
  port: 8003

spring:
  application:
    name: hystrix-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@replica1:8001/eureka/,http://root:root@replica2:8002/eureka/

service-url:
  user-service: http://user-service