spring:
  application:
    name: user-local-service

server:
  port: 8004
  servlet:
    session:
      cookie:
        name: ${spring.application.name}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@replica1:8101/eureka/,http://root:root@replica2:8102/eureka/
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

logging:
  level:
    root: INFO
