server:
  port: 8006

logging:
  level: #修改日志级别
    cn.jzyan: DEBUG

spring:
  application:
    name: ribbon-local-service

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://root:root@replica1:8101/eureka/,http://root:root@replica2:8102/eureka/
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}

user-service:
  name: user-local-service
