spring:
  profiles:
    active: @profileActive@

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
    readTimeout: 6000
    connectTimeout: 3000
    writeTimeout: 6000
    maxIdleConnections: 50
    keepAliveDuration: 10
