server:
  port: 8005

spring:
  application:
    name: oauth2-local-service

#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://root:root@replica1:8101/eureka/,http://root:root@replica2:8102/eureka/

logging:
  level:
    org.springframework.security: DEBUG
