server:
  port: 8102

spring:
  application:
    name: eureka-security-server
  security:
    user:
      name: root
      password: root

eureka:
  instance:
    hostname: replica2
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 注册到另一个Eureka注册中心
      defaultZone: http://root:root@replica1:8101/eureka/

logging:
  level:
    root: INFO
